# Shamelessly stolen from https://forums.raspberrypi.com/viewtopic.php?t=311235
# Heavily edited, incl. multithreading
from machine import Pin, PWM
from utime import sleep_us, sleep
import picozero, _thread

pwm_pin = 15
pwm = PWM(Pin(pwm_pin))

freq = 500*1000
pwm.freq(freq)

# Lookup table - generated by https://www.daycounter.com/Calculators/Sine-Generator-Calculator.phtml
# Max Amplitude: 65535, Decimal
duty_sine_int = [32768,34911,37045,39160,41248,43300,45307,47260,49151,50972,52715,54373,55938,57403,58764,60013,61145,62156,63041,63796,64418,64905,65255,65465,65535,65465,65255,64905,64418,63796,63041,62156,61145,60013,58764,57403,55938,54373,52715,50972,49151,47260,45307,43300,41248,39160,37045,34911,32768,30624,28490,26375,24287,22235,20228,18275,16384,14563,12820,11162,9597,8132,6771,5522,4390,3379,2494,1739,1117,630,280,70,0,70,280,630,1117,1739,2494,3379,4390,5522,6771,8132,9597,11162,12820,14563,16384,18275,20228,22235,24287,26375,28490,30624]

def sine(pwm, duty_sine_int):
    while True:
        for x in duty_sine_int:
            lock.acquire()
            pwm.duty_u16(x)
            lock.release()

lock = _thread.allocate_lock()
_thread.start_new_thread(sine, (pwm, duty_sine_int))
    
while True:
    if not lock.locked():
        print(f"CPU temp: {picozero.pico_temp_sensor.temp}°C")
        sleep(1)
